### ISSUE TITLE
Failed to start instance ...

### ISSUE THREAD

**Issue by brknkfr** [williamkray/maubot-gifme#20]
There seems to be a problem with maubot 0.5.0. When I try to enable a `gifme` instance, maubot throws an error. I think, something is wrong with the database.

```
Oct 04 10:50:46 matrix-server python3[336695]: [2024-10-04 10:50:46,467] [ERROR@maubot.instance.gifme] Failed to start instance database
Oct 04 10:50:46 matrix-server python3[336695]: Traceback (most recent call last):
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/maubot/instance.py", line 371, in start
Oct 04 10:50:46 matrix-server python3[336695]:     await self.start_database(cls.get_db_upgrade_table())
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/maubot/instance.py", line 325, in start_database
Oct 04 10:50:46 matrix-server python3[336695]:     await self.inst_db.start()
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/maubot/lib/plugin_db.py", line 60, in start
Oct 04 10:50:46 matrix-server python3[336695]:     await super().start()
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/mautrix/util/async_db/database.py", line 105, in start
Oct 04 10:50:46 matrix-server python3[336695]:     await self.upgrade_table.upgrade(self)
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/mautrix/util/async_db/upgrade.py", line 137, in upgrade
Oct 04 10:50:46 matrix-server python3[336695]:     version = await upgrade(conn, db.scheme) or new_version
Oct 04 10:50:46 matrix-server python3[336695]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/mautrix/util/async_db/upgrade.py", line 35, in _wrapper
Oct 04 10:50:46 matrix-server python3[336695]:     return await _wrapped(conn)
Oct 04 10:50:46 matrix-server python3[336695]:            ^^^^^^^^^^^^^^^^^^^^
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/plugins/org.jobmachine.gifme-v0.1.0.mbp/gifme/db.py", line 9, in upgrade_v1
Oct 04 10:50:46 matrix-server python3[336695]:     await conn.execute(
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/mautrix/util/async_db/connection.py", line 38, in wrapper
Oct 04 10:50:46 matrix-server python3[336695]:     ret = await func(self, arg, *args, **kwargs)
Oct 04 10:50:46 matrix-server python3[336695]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/mautrix/util/async_db/connection.py", line 81, in execute
Oct 04 10:50:46 matrix-server python3[336695]:     return await self.wrapped.execute(query, *args, timeout=timeout)
Oct 04 10:50:46 matrix-server python3[336695]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 04 10:50:46 matrix-server python3[336695]:   File "/opt/maubot/lib/python3.11/site-packages/asyncpg/connection.py", line 317, in execute
Oct 04 10:50:46 matrix-server python3[336695]:     return await self._protocol.query(query, timeout)
Oct 04 10:50:46 matrix-server python3[336695]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 04 10:50:46 matrix-server python3[336695]:   File "asyncpg/protocol/protocol.pyx", line 338, in query
Oct 04 10:50:46 matrix-server python3[336695]: asyncpg.exceptions.PostgresSyntaxError: syntax error at or near "VIRTUAL"
Oct 04 10:50:46 matrix-server python3[336695]: [2024-10-04 10:50:46,486] [INFO@aiohttp.access] 10.0.9.10 "PUT /_matrix/maubot/v1/instance/gifme 200 417 in 0.0694s"
```

**Comment by williamkray** [comment]
i see `PostgresSyntaxError` in your error... are you using postgres for your plugin databases?

[per the readme](https://github.com/williamkray/maubot-gifme/blob/a896a07fba53c90455431e79904f79d949c91f92/README.md?plain=1#L4), this plugin is only tested and assumed to work using sqlite as the plugin database.
